/**
 * 主题 CSS 生成器：读 lib/themes.ts（单一源）→ 写 app/themes.generated.css。
 * 用法：npm run gen:themes（predev/prebuild 会自动跑；dev:themes 可监听改动）。
 *
 * 输出：裸 :root = DEFAULT_THEME 值（SSR 首屏 + 无 JS 兜底）；再为每套主题输出
 *      :root[data-theme="<id>"] { ... } 覆盖块（特异性 (0,2,0) > 裸 :root，必胜）。
 *
 * 关键：每套主题同时输出 raw 原语 + 语义层 + 渐变——因为 globals.css 里有规则
 *      直接引用 raw（var(--white-2)/var(--jet)…），光改语义层它们不跟随。
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  THEMES,
  DEFAULT_THEME_ID,
  ON_IMAGE_BG,
  ON_IMAGE_FG,
  type Theme,
  type ThemeColors,
} from "../lib/themes";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "..", "app", "themes.generated.css");

/** #RRGGBB → rgba(r,g,b,a) */
function hexToRgba(hex: string, alpha: number): string {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

/** 中性结构渐变（按底色派生，深浅模式都成立） */
function neutralGradients(c: ThemeColors) {
  return {
    "--bg-gradient-onyx": `linear-gradient(to bottom right, ${c.bgElevated} 3%, ${c.bgSecondary} 97%)`,
    "--bg-gradient-jet": `linear-gradient(to bottom right, ${hexToRgba(
      c.borderColor,
      0.25
    )} 0%, transparent 100%), ${c.bgSecondary}`,
    "--border-gradient-onyx": `linear-gradient(to bottom right, ${c.borderColor} 0%, transparent 50%)`,
  };
}

/** 强调色渐变（同色相明暗，从 accentLight/accentDark 派生） */
function accentGradients(c: ThemeColors) {
  return {
    "--bg-gradient-yellow-1": `linear-gradient(to bottom right, ${c.accentLight} 0%, ${hexToRgba(
      c.accentLight,
      0
    )} 50%)`,
    "--bg-gradient-yellow-2": `linear-gradient(135deg, ${hexToRgba(
      c.accentLight,
      0.251
    )} 0%, ${hexToRgba(c.accentDark, 0)} 59.86%), ${c.bgSecondary}`,
    "--text-gradient-yellow": `linear-gradient(to right, ${c.accentLight}, ${c.accentDark})`,
  };
}

/** raw 原语（globals.css 有规则直接引用，必须随主题覆盖） */
function rawPrimitives(c: ThemeColors) {
  return {
    "--smoky-black": c.bgPrimary,
    "--eerie-black-1": c.bgSecondary,
    "--eerie-black-2": c.bgCard,
    "--onyx": c.bgElevated,
    "--jet": c.borderColor,
    "--white-1": c.textPrimary,
    "--white-2": c.textPrimary,
    "--light-gray": c.textSecondary,
    "--light-gray-70": c.textMuted,
    "--orange-yellow-crayola": c.accentPrimary,
    "--vegas-gold": c.accentSecondary,
    "--bittersweet-shimmer": c.danger,
  };
}

/** 语义层 + 语义色 + 结构色 */
function semantic(c: ThemeColors) {
  return {
    "--bg-primary": c.bgPrimary,
    "--bg-secondary": c.bgSecondary,
    "--bg-card": c.bgCard,
    "--bg-elevated": c.bgElevated,
    "--text-primary": c.textPrimary,
    "--text-secondary": c.textSecondary,
    "--text-muted": c.textMuted,
    "--text-inverse": c.textInverse,
    "--accent-primary": c.accentPrimary,
    "--accent-secondary": c.accentSecondary,
    "--accent-light": c.accentLight,
    "--accent-dark": c.accentDark,
    "--accent-hover": c.accentLight,
    "--border-color": c.borderColor,
    "--border-light": c.borderLight,
    "--divider-color": c.dividerColor,
    "--danger": c.danger,
    "--danger-bg": c.dangerBg,
    "--success": c.success,
    "--success-bg": c.successBg,
    "--warning": c.warning,
    "--warning-bg": c.warningBg,
    "--navbar-bg": c.navbarBg,
    "--scrollbar-thumb": c.scrollbarThumb,
    "--scrollbar-thumb-hover": c.scrollbarThumbHover,
    "--scrim": c.scrim,
    "--bg-code": c.bgCode,
    "--text-on-danger": c.textOnDanger,
    "--on-image-bg": ON_IMAGE_BG,
    "--on-image-fg": ON_IMAGE_FG,
  };
}

function blockFor(theme: Theme): string {
  const c = theme.colors;
  const all = {
    ...rawPrimitives(c),
    ...neutralGradients(c),
    ...accentGradients(c),
    ...semantic(c),
  };
  const selector =
    theme.id === DEFAULT_THEME_ID ? ":root" : `:root[data-theme="${theme.id}"]`;
  const lines = Object.entries(all).map(
    ([k, v]) => `  ${k}: ${v};`
  );
  return `/* ${theme.name} (${theme.mode}) */\n${selector} {\n${lines.join("\n")}\n}`;
}

const header = `/* AUTO-GENERATED by scripts/gen-theme-css.ts — 请勿手改。
 * 单一源：lib/themes.ts。改完跑 npm run gen:themes。
 * 裸 :root = ${DEFAULT_THEME_ID}（SSR 首屏 + 无 JS 兜底）；其余为 :root[data-theme] 覆盖块。
 * 入库如 lockfile（确定性产物），globals.css 顶部 @import 引入。
 */

`;

const css = header + THEMES.map(blockFor).join("\n\n") + "\n";

writeFileSync(OUT, css, "utf8");
console.log(`✓ 生成 ${THEMES.length} 套主题 → ${OUT}`);
